### ISSUE TITLE
bug: Export is not working with cutter 2.0

### ISSUE THREAD

**Issue by FlyCrafting** [yossizap/x64dbgcutter#1]
It looks like plugin doesnt work with Cutter 2.0.
When I try to export a database, console says me
```
[x64dbg-cutter]: Exporting database to D:/test.dd32
Command 'evj' does not exist.
```
and file won't appear.

**Comment by yossizap** [comment]
Thank you for opening an issue! It should work now but let me know if something else breaks with this release. The issue was caused by newshell changes in Rizin.
