### ISSUE TITLE
feat: Suggest an extension while exporting database

### ISSUE THREAD

**Issue by FlyCrafting** [yossizap/x64dbgcutter#2]
When I try to export a database, it doesn't suggest any extensions and saves it without extension by default.
Its readable by x64dbg but it I need to manually choose * all files option here. It would be better if plugin will suggest an extension (.dd32 or .dd64) for database, it will be easier for x64dbg to read it.

**Comment by yossizap** [comment]
Thank you for the suggestion 👍 I couldn't find a way to suggest an extension with PySide's API but I added a filter for .dd64/32 extensions in the file dialog and I auto append the extension to the filename if the user didn't write it manually.
